version: "3.8"
services:
  database:
    image: postgres
    restart: "unless-stopped"
    environment:
      POSTGRES_DB: "mypostgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mypassword"
    ports:
      - '5432:5432'

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-clean-todo-image/version1.0
    depends_on:
      - database
    ports:
     - '8080:8080'